export const DEFAULT_CATEGORIES: string[] = [
  'planner',
  'budget tracker',
  'habit tracker',
  'gratitude journal',
  'meal planner',
  'fitness tracker',
  'reading log',
  'goal setting worksheet',
  'daily planner',
  'weekly planner',
  'monthly calendar',
  'to-do list',
  'study planner',
  'wedding planner',
  'travel planner',
  'cleaning schedule',
  'self-care tracker',
  'mood tracker',
  'water intake tracker',
  'savings tracker',
];
